title: Configuration file that maps fields to forensicstore
order: 20
backends:
  - SQL
fieldmappings:
  a0: Null
  a1: Null
  a2: Null
  a3: Null
  Accesses: Null
  AccessList: Null
  AccessMask: Null
  AccountName: EventData.SamAccountName
  action: Null
  AllowedToDelegateTo: EventData.AllowedToDelegateTo
  answer: Null
  AttributeLDAPDisplayName: Null
  AttributeValue: Null
  AuditPolicyChanges: Null
  AuthenticationPackageName: Null
  c-uri: Null
  c-uri-extension: Null
  c-uri-query: Null
  c-uri-stem: Null
  c-useragent: Null
  CallingProcessName: Null
  CallTrace: Null
  cipher: Null
  Command: Null
  CommandLine: EventData.CommandLine
  Company: Null
  ComputerName: Null
  ContextInfo: Null
  cs-cookie: Null
  cs-host: Null
  cs-method: Null
  CurrentDirectory: Null
  Description: Null
  Destination: Null
  DestinationAddress: Null
  DestinationHostname: Null
  DestinationIp: Null
  DestinationIsIpv6: Null
  DestinationPort: Null
  DestPort: Null
  Details: Null
  Device: Null
  DeviceClassName: Null
  DeviceDescription: Null
  dst_ip: Null
  EngineVersion: Null
  event.category: Null
  EventID: System.EventID.Value
  eventName: Null
  eventSource: Null
  EventType: Null
  eventType: Null
  exe: Null
  FailureCode: Null
  FileName: Null
  FileVersion: Null
  GrantedAccess: Null
  GroupName: Null
  GroupSid: Null
  HiveName: Null
  host.scan.vuln: Null
  host.scan.vuln_name: Null
  HostApplication: Null
  HostName: Null
  HostVersion: Null
  Image: EventData.ProcessName
  ImageLoaded: Null
  ImagePath: Null
  Imphash: Null
  Initiated: Null
  IntegrityLevel: Null
  IpAddress: EventData.IpAddress
  key: Null
  KeyLength: EventData.KeyLength
  keywords: System.Keywords
  Keywords: System.Keywords
  LayerRTID: Null
  LDAPDisplayName: Null
  Level: System.Level
  LogonId: EventData.SubjectLogonId
  LogonProcessName: EventData.LogonProcessName
  LogonType: EventData.LogonType
  Message: Null
  name: Null
  NewName: Null
  NewProcessName: EventData.NewProcessName
  ObjectName: Null
  ObjectServer: Null
  ObjectType: Null
  OriginalFilename: Null
  OriginalFileName: Null
  pam_message: Null
  pam_rhost: Null
  pam_user: Null
  ParentCommandLine: Null
  ParentImage: EventData.ParentProcessName
  ParentIntegrityLevel: Null
  ParentUser: Null
  parent_domain: Null
  PasswordLastSet: EventData.PasswordLastSet
  Path: Null
  PipeName: Null
  PrivilegeList: EventData.PrivilegeList
  ProcessCommandLine: Null
  ProcessName: EventData.ProcessName
  Product: Null
  Properties: Null
  query: Null
  QueryName: Null
  QueryResults: Null
  QueryStatus: Null
  r-dns: Null
  record_type: Null
  RelativeTargetName: Null
  requestParameters.attribute: Null
  requestParameters.userData: Null
  request_type: Null
  responseElements.pendingModifiedValues.masterUserPassword: Null
  responseElements.publiclyAccessible: Null
  SAMAccountName: Null
  sc-status: Null
  ScriptBlockText: Null
  service: Null
  Service: Null
  ServiceFileName: Null
  ServiceName: Null
  ServicePrincipalNames: Null
  ShareName: Null
  SidHistory: EventData.SidHistory
  Signature: Null
  Signed: Null
  Source: Null
  SourceAddress: Null
  SourceImage: Null
  SourceNetworkAddress: Null
  SourcePort: Null
  src_ip: Null
  StartFunction: Null
  StartModule: Null
  Status: EventData.Status
  SubjectDomainName: EventData.SubjectDomainName
  SubjectLogonId: EventData.SubjectLogonId
  SubjectUserName: EventData.SubjectUserName
  SubjectUserSid: EventData.SubjectUserSid
  SYSCALL: Null
  TargetFileName: Null
  TargetFilename: Null
  TargetImage: Null
  TargetObject: Null
  TargetProcessAddress: Null
  TargetUserName: EventData.TargetUserName
  TicketEncryptionType: Null
  TicketOptions: Null
  type: Null
  User: Null
  userIdentity.arn: Null
  userIdentity.type: Null
  Username: Null
  UserName: Null
  Value: Null
  Workstation: EventData.Workstation
  WorkstationName: EventData.WorkstationName
