name: Release

on:
  release:
    types: [published]

jobs:
  docker:
    name: Docker Hub Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: forensicanalysis/plaso
          tag_with_ref: true
          path: plaso
          continue-on-error: true

      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: forensicanalysis/artifacts
          tag_with_ref: true
          path: artifacts
          # continue-on-error: true
