name: Release

on:
  push:
    branches: [master]
  release:
    types: [published]

jobs:
  docker:
    name: Publish Docker
    runs-on: ubuntu-latest
    strategy:
      matrix:
        plugin: ['import-image', 'plaso', 'shimcache', 'yara', 'sigma']
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: forensicanalysis/elementary-${{ matrix.plugin }}
          tag_with_ref: true
          path: ${{ matrix.plugin }}
